module.exports = {
  apps: [
    {
      name: 'medusa-backend',
      script: 'npm',
      args: 'run start',
      cwd: './fashun-medusa-backend',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 9000,
      },
      error_file: './logs/medusa-error.log',
      out_file: './logs/medusa-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
    },
    {
      name: 'frontend',
      script: 'npm',
      args: 'run start',
      cwd: './fashun-store',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
    },
    {
      name: 'meilisearch',
      script: './meilisearch',
      args: '--master-key=MASTER_KEY --db-path=./meili_data',
      autorestart: true,
      max_memory_restart: '500M',
    },
  ],
};
