name: Performance Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd fashun-store
          npm install
      
      - name: Build
        run: |
          cd fashun-store
          npm run build
      
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            http://localhost:3000
            http://localhost:3000/collections/all
            http://localhost:3000/products/test
          uploadArtifacts: true
          temporaryPublicStorage: true
          
      - name: Check Performance
        run: |
          if [ $(cat .lighthouseci/manifest.json | jq '.[] | .summary.performance' | awk '{if($1<0.9) print "fail"}' | wc -l) -gt 0 ]; then
            echo "❌ Performance score below 90"
            exit 1
          else
            echo "✅ Performance check passed"
          fi
